version: '3.9'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - database
    networks:
      - banking
  database:
    image: "postgres" # use latest official postgres version
    env_file:
      - database.env # configure postgres
    networks:
      - banking
networks:
  banking:
    driver: bridge

